services:
  mongodb:
    image: mongodb/mongodb-community-server:5.0.22-ubi8
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
  mongodb_dev:
    image: mongodb/mongodb-community-server:5.0.22-ubi8
    volumes:
      - mongodata_dev:/data/db
    ports:
      - 27018:27018
    command: --port 27018
volumes:
  mongodata:
  mongodata_dev:
